package ru.autoauction.web;

import jakarta.servlet.http.HttpSession;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.autoauction.config.AppProperties;
import ru.autoauction.model.*;
import ru.autoauction.repo.*;
import ru.autoauction.service.*;
import java.io.IOException;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import static ru.autoauction.web.ApiDtos.*;

@RestController @RequestMapping("/api/admin")
public class AdminController {
  private static final Logger log=LoggerFactory.getLogger(AdminController.class);
  private final CurrentUser current;private final LotRepository lots;private final BidRepository bids;private final UserRepository users;private final BroadcastRepository broadcasts;private final AuctionService auction;private final MaxBotService bot;private final AppProperties props;private final ApplicationEventPublisher eventPublisher;private final ImageStorageService images;private final AuctionEvents events;
  public AdminController(CurrentUser current,LotRepository lots,BidRepository bids,UserRepository users,BroadcastRepository broadcasts,AuctionService auction,MaxBotService bot,AppProperties props,ApplicationEventPublisher eventPublisher,ImageStorageService images,AuctionEvents events){this.current=current;this.lots=lots;this.bids=bids;this.users=users;this.broadcasts=broadcasts;this.auction=auction;this.bot=bot;this.props=props;this.eventPublisher=eventPublisher;this.images=images;this.events=events;}
  public record StepRequest(@Positive long step){} public record BroadcastRequest(@NotBlank @Size(max=4000) String text){} public record BanRequest(@NotNull Boolean banned){}
  public record LotRequest(@NotBlank @Size(max=200) String title,@NotBlank @Size(max=5000) String description,String vin,String mileage,@PositiveOrZero Integer ownersCount,String engineNumber,String fuelType,String engineVolume,String horsepower,String transmission,String driveType,String autotecaUrl,@NotNull @PositiveOrZero Long startingPrice,@NotNull @Positive Long bidStep,@NotNull @Positive @Max(525_600) Long durationMinutes,boolean publish){}
  public record AdminUserDto(Long id,Long maxUserId,String name,String phone,Role role,boolean registered,boolean banned,Instant createdAt,Instant lastSeenAt){
    static AdminUserDto of(AppUser u){return new AdminUserDto(u.id,u.maxUserId,u.name,u.phone,u.role,u.registered,Boolean.TRUE.equals(u.banned),u.createdAt,u.lastSeenAt);}
  }
  public record Stats(long users,long onlineUsers,long lots,long liveLots,long bids,long bidVolume,long broadcasts){}
  public record Presence(long onlineUsers,Map<Long,Long> lots){}
  @GetMapping("/stats") public Stats stats(HttpSession s){current.requireAdmin(s);Instant now=Instant.now();long active=lots.findByStatusAndStartsAtLessThanEqualAndEndsAtGreaterThanOrderByEndsAtAsc(LotStatus.LIVE,now,now).size();long registered=users.findAll().stream().filter(u->u.registered&&!isDemoUser(u)).count();return new Stats(registered,events.onlineUsers(),lots.count(),active,bids.count(),bids.totalBidVolume(),broadcasts.count());}
  @GetMapping("/presence") public Presence presence(HttpSession s){current.requireAdmin(s);return new Presence(events.onlineUsers(),events.onlineByLot());}
  @GetMapping("/users") @Transactional public List<AdminUserDto> users(HttpSession s){
    current.requireAdmin(s);
    List<AppUser> all=users.findAll();
    if(all.stream().mapToInt(u->synchronizeConfiguredRole(u)?1:0).sum()>0)users.saveAll(all);
    return all.stream().filter(u->!isDemoUser(u)).sorted(Comparator.comparing((AppUser u)->u.registered).reversed().thenComparing(u->u.createdAt,Comparator.reverseOrder())).map(AdminUserDto::of).toList();
  }
  @PatchMapping("/users/{id}/make-admin") @Transactional public AdminUserDto makeAdmin(@PathVariable long id,HttpSession s){
    AppUser actor=current.requireSuperAdmin(s);
    AppUser target=users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Пользователь не найден"));
    synchronizeConfiguredRole(target);
    if(target.role==Role.SUPER_ADMIN)return AdminUserDto.of(target);
    if(Boolean.TRUE.equals(target.banned))throw new ResponseStatusException(HttpStatus.CONFLICT,"Сначала разблокируйте пользователя");
    target.role=Role.ADMIN;
    AppUser saved=users.save(target);
    log.info("Пользователь MAX {} назначен администратором пользователем MAX {}",saved.maxUserId,actor.maxUserId);
    return AdminUserDto.of(saved);
  }
  @PatchMapping("/users/{id}/ban") @Transactional public AdminUserDto ban(@PathVariable long id,@Valid @RequestBody BanRequest req,HttpSession s){AppUser actor=current.requireAdmin(s);AppUser target=users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Пользователь не найден"));synchronizeConfiguredRole(target);if(target.id.equals(actor.id))throw new ResponseStatusException(HttpStatus.CONFLICT,"Нельзя заблокировать свой аккаунт");if(target.role!=Role.USER)throw new ResponseStatusException(HttpStatus.CONFLICT,"Администратора сначала нужно лишить прав");target.banned=req.banned;target.bannedAt=req.banned?Instant.now():null;AppUser saved=users.save(target);if(req.banned)events.disconnectUser(target.id);log.info("Пользователь MAX {} {} пользователем MAX {}",target.maxUserId,req.banned?"заблокирован":"разблокирован",actor.maxUserId);return AdminUserDto.of(saved);}
  @PatchMapping("/lots/{id}/step") public Map<String,Object> step(@PathVariable long id,@RequestBody StepRequest req,HttpSession s){current.requireAdmin(s);Lot l=auction.updateStep(id,req.step);return Map.of("id",l.id,"bidStep",l.bidStep);}
  @PatchMapping("/lots/{id}/status") @Transactional public void status(@PathVariable long id,@RequestParam LotStatus value,HttpSession s){current.requireAdmin(s);Lot l=lots.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Лот не найден"));boolean launching=l.status!=LotStatus.LIVE&&value==LotStatus.LIVE;if(launching){Duration duration=Duration.between(l.startsAt,l.endsAt);if(duration.isNegative()||duration.isZero())duration=Duration.ofHours(1);l.startsAt=Instant.now();l.endsAt=l.startsAt.plus(duration);}l.status=value;lots.save(l);if(launching)eventPublisher.publishEvent(new LotStartedEvent(l.id,l.title,l.startingPrice));}
  @PostMapping("/lots/{id}/restart") @Transactional public Map<String,Long> restart(@PathVariable long id,HttpSession s) throws IOException {current.requireAdmin(s);Lot source=lots.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Лот не найден"));Instant now=Instant.now();boolean finished=source.status==LotStatus.FINISHED||(source.status==LotStatus.LIVE&&!now.isBefore(source.endsAt));if(!finished)throw new ResponseStatusException(HttpStatus.CONFLICT,"Перезапустить можно только завершённый лот");Duration duration=Duration.between(source.startsAt,source.endsAt);if(duration.isNegative()||duration.isZero())duration=Duration.ofHours(1);Lot restarted=copyLot(source);restarted.currentPrice=restarted.startingPrice;restarted.startsAt=now;restarted.endsAt=now.plus(duration);restarted.status=LotStatus.LIVE;lots.save(restarted);copyMedia(source,restarted);lots.save(restarted);eventPublisher.publishEvent(new LotStartedEvent(restarted.id,restarted.title,restarted.startingPrice));return Map.of("id",restarted.id,"sourceId",source.id);}
  @PostMapping("/lots/{id}/cancel") @Transactional public void cancel(@PathVariable long id,HttpSession s){current.requireAdmin(s);Lot l=lots.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Лот не найден"));if(l.status==LotStatus.CANCELLED)return;if(l.status!=LotStatus.LIVE)throw new ResponseStatusException(HttpStatus.CONFLICT,"Отменить можно только активный аукцион");l.status=LotStatus.CANCELLED;l.endsAt=Instant.now();lots.save(l);eventPublisher.publishEvent(new LotCancelledEvent(l.id));}
  @PostMapping("/broadcast") public BroadcastLog broadcast(@RequestBody BroadcastRequest req,HttpSession s){current.requireAdmin(s);List<AppUser> audience=users.findAll().stream().filter(u->u.registered&&!Boolean.TRUE.equals(u.banned)&&!isDemoUser(u)).toList();int delivered=0;for(AppUser u:audience){try{if(bot.sendText(u.maxUserId,req.text))delivered++;}catch(Exception ignored){}}return broadcasts.save(new BroadcastLog(req.text,audience.size(),delivered));}
  @PostMapping(value="/lots",consumes="application/json") @Transactional public Map<String,Long> create(@Valid @RequestBody LotRequest req,HttpSession s){current.requireSuperAdmin(s);Lot lot=new Lot();lot.status=LotStatus.DRAFT;applyLot(lot,req,true);lots.save(lot);return Map.of("id",lot.id);}
  @PutMapping(value="/lots/{id}",consumes="application/json") @Transactional public Map<String,Long> edit(@PathVariable long id,@Valid @RequestBody LotRequest req,HttpSession s){current.requireAdmin(s);Lot lot=lots.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Лот не найден"));applyLot(lot,req,false);lots.save(lot);return Map.of("id",lot.id);}
  @PostMapping(value="/lots/{id}/media",consumes="multipart/form-data") @Transactional public MediaDto uploadMedia(@PathVariable long id,@RequestPart("media") MultipartFile file,HttpSession s) throws IOException {current.requireAdmin(s);Lot lot=lots.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Лот не найден"));if(file.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Файл пустой");String type=mediaType(file);Path dir=Files.createDirectories(Path.of(props.uploadDir()).resolve(String.valueOf(lot.id)));String contentType=Objects.requireNonNullElse(file.getContentType(),"");String name;if("image".equals(type))name=images.store(file,dir,contentType);else{name=UUID.randomUUID()+fileExtension(file,type);Files.copy(file.getInputStream(),dir.resolve(name),StandardCopyOption.REPLACE_EXISTING);}int order=lot.media.stream().mapToInt(m->m.sortOrder).max().orElse(-1)+1;LotMedia media=new LotMedia(lot,"/uploads/"+lot.id+"/"+name,type,order);lot.media.add(media);lots.save(lot);return new MediaDto(media.id,media.url,media.type);}
  @DeleteMapping("/lots/{lotId}/media/{mediaId}") @Transactional public void deleteMedia(@PathVariable long lotId,@PathVariable long mediaId,HttpSession s) throws IOException {current.requireAdmin(s);Lot lot=lots.findById(lotId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Лот не найден"));LotMedia media=lot.media.stream().filter(m->m.id.equals(mediaId)).findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Файл не найден"));lot.media.remove(media);lots.save(lot);String prefix="/uploads/"+lot.id+"/";if(media.url.startsWith(prefix)){String filename=media.url.substring(prefix.length());if(!filename.contains("/")&&!filename.contains(".."))Files.deleteIfExists(Path.of(props.uploadDir()).resolve(String.valueOf(lot.id)).resolve(filename));}}
  private void applyLot(Lot lot,LotRequest req,boolean creating){lot.title=req.title.trim();lot.description=req.description.trim();lot.vin=blankToNull(req.vin);lot.mileage=blankToNull(req.mileage);lot.ownersCount=req.ownersCount;lot.engineNumber=blankToNull(req.engineNumber);lot.fuelType=blankToNull(req.fuelType);lot.engineVolume=blankToNull(req.engineVolume);lot.horsepower=blankToNull(req.horsepower);lot.transmission=blankToNull(req.transmission);lot.driveType=blankToNull(req.driveType);lot.autotecaUrl=blankToNull(req.autotecaUrl);lot.startingPrice=req.startingPrice;if(creating||bids.countByLotId(lot.id)==0)lot.currentPrice=req.startingPrice;lot.bidStep=req.bidStep;Instant now=Instant.now();if(creating||lot.status!=LotStatus.LIVE)lot.startsAt=now;lot.endsAt=now.plus(Duration.ofMinutes(req.durationMinutes));}
  private Lot copyLot(Lot source){Lot copy=new Lot();copy.title=source.title;copy.description=source.description;copy.vin=source.vin;copy.mileage=source.mileage;copy.ownersCount=source.ownersCount;copy.engineNumber=source.engineNumber;copy.fuelType=source.fuelType;copy.engineVolume=source.engineVolume;copy.horsepower=source.horsepower;copy.transmission=source.transmission;copy.driveType=source.driveType;copy.autotecaUrl=source.autotecaUrl;copy.startingPrice=source.startingPrice;copy.bidStep=source.bidStep;return copy;}
  private void copyMedia(Lot source,Lot target) throws IOException {Path targetDir=null;String prefix="/uploads/"+source.id+"/";for(LotMedia media:source.media){String url=media.url;if(url.startsWith(prefix)){String filename=url.substring(prefix.length());if(!filename.contains("/")&&!filename.contains("..")){Path original=Path.of(props.uploadDir()).resolve(String.valueOf(source.id)).resolve(filename);if(Files.isRegularFile(original)){if(targetDir==null)targetDir=Files.createDirectories(Path.of(props.uploadDir()).resolve(String.valueOf(target.id)));String extension=filename.lastIndexOf('.')>=0?filename.substring(filename.lastIndexOf('.')):"";String copiedName=UUID.randomUUID()+extension;Files.copy(original,targetDir.resolve(copiedName),StandardCopyOption.REPLACE_EXISTING);url="/uploads/"+target.id+"/"+copiedName;}}}target.media.add(new LotMedia(target,url,media.type,media.sortOrder));}}
  private String mediaType(MultipartFile file){String content=Objects.requireNonNullElse(file.getContentType(),"").toLowerCase(Locale.ROOT),ext=fileExtension(file,"");if(content.startsWith("image/")||ext.matches("\\.(jpg|jpeg|png|webp|gif)"))return "image";if(content.startsWith("video/")||ext.matches("\\.(mp4|mov|webm)"))return "video";throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Разрешены JPG, PNG, WebP, GIF, MP4, MOV и WebM");}
  private String blankToNull(String value){return value==null||value.isBlank()?null:value.trim();}
  private boolean synchronizeConfiguredRole(AppUser user){Role expected=props.superAdminMaxIds().contains(user.maxUserId)?Role.SUPER_ADMIN:props.adminMaxIds().contains(user.maxUserId)?Role.ADMIN:null;if(expected==null||user.role==expected)return false;user.role=expected;return true;}
  private String fileExtension(MultipartFile file,String type){String original=Objects.requireNonNullElse(file.getOriginalFilename(),"");int dot=original.lastIndexOf('.');if(dot>=0&&dot<original.length()-1){String ext=original.substring(dot).toLowerCase(Locale.ROOT);if(ext.matches("\\.(jpg|jpeg|png|webp|gif|mp4|mov|webm)"))return ext;}return "video".equals(type)?".mp4":".jpg";}
  private boolean isDemoUser(AppUser user){if(props.demoAuth()||props.adminMaxIds().contains(user.maxUserId)||props.superAdminMaxIds().contains(user.maxUserId))return false;return (user.maxUserId==1000001L&&"Алексей Воронцов".equals(user.name))||(user.maxUserId==1000002L&&"Мария Соколова".equals(user.name));}
}
